language: node_js

node_js:
  - "6.0"
  - "6.1"

services:

before_script:
 - "npm i -g process-nextick-args util-deprecate"

notifications:
  email: true

# whitelisted branches
branches:
  only:
    - master