sudo: required

language: node_js

node_js:
  - "6"

apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable

env:
  - CHROME_BIN=google-chrome
  - DISPLAY=:99.0

before_install:
  — sh -e /etc/init.d/xvfb start

before_script:
  - npm install -g angular-cli

notifications:
  email: true

# whitelisted branches
branches:
  only:
    - master